### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#114]
```python
Traceback (most recent call last):
  File "modules/mod_iq_disco.py", line 114, in checkAPIToken
    name = vk.getUserData(userID)
  File "library/utils.py", line 87, in wrapper
    if uid in self.cache:
TypeError: unhashable type: 'dict'
```

**Comment by mrDoctorWho** [comment]
Блокируется #120

**Comment by mrDoctorWho** [comment]
Не нужно.
