### ISSUE TITLE
Ошибка разбора вложений

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#125]
```python
Traceback (most recent call last):
  File "./gateway.py", line 669, in sendMessages
    result = func(self, message)
  File "extensions/attachments.py", line 52, in parseAttachments
    name = "“%s”" % self.vk.getGroupData(tid)["name"]
  File "library/utils.py", line 95, in wrapper
    result = func(self, uid, fields)
  File "./gateway.py", line 448, in getGroupData
    data = data[0]
KeyError: 0
```

**Comment by mrDoctorWho** [comment]
Не починено, и не будет. Mark 2 будет написан с нуля, проблема неактуальна.
