### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sock'

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#132]
| 02.10.2016 (20:08:38) |
```python
Traceback (most recent call last):
  File "library/longpoll.py", line 72, in add
    cls.__add(some_user)
  File "library/longpoll.py", line 43, in __add
    cls.__list[opener.sock] = (user, opener)
AttributeError: 'NoneType' object has no attribute 'sock'
```

**Comment by mrDoctorWho** [comment]
Fixed in bbc960130ad0e7550feaed76d4121e269731494f
