### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#136]
| 15.11.2016 (06:02:46) |
```python
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "modules/mod_iq_register.py", line 22, in initializeUser
    user.initialize(resource=resource)
  File "./gateway.py", line 605, in initialize
    self.friends = self.vk.getFriends()
  File "./gateway.py", line 412, in getFriends
    for friend in raw:
TypeError: 'NoneType' object is not iterable
```

**Comment by mrDoctorWho** [comment]
Fixed in 604fc6630f3884958764a05055ec72fbaa5e9c2b
