### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#142]
| 22.11.2016 (13:11:41) |
```python
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "modules/mod_iq_vcard.py", line 109, in vcard_handler
    vcard = buildVcard(VCARD_TEMPLATE)
  File "modules/mod_iq_vcard.py", line 78, in buildVcard
    vcard.setTagData(key, VCARD_FIELDS[key] % data)
KeyError: 'id'
```

**Comment by mrDoctorWho** [comment]
38f99047ae29861292a54bbd0eabb38fa30ce80a
