### ISSUE TITLE
AttributeError: 'VK' object has no attribute 'vk'

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#148]
```python
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "extensions/captcha_forms.py", line 19, in sendCaptcha
    msg.setID(user.vk.engine.captcha["sid"])
AttributeError: 'VK' object has no attribute 'vk'
```

**Comment by mrDoctorWho** [comment]
| 21.01.2017 (22:01:30) |
```python
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "extensions/captcha_forms.py", line 19, in sendCaptcha
    msg.setID(vk.engine.captcha["sid"])
AttributeError: 'User' object has no attribute 'engine'
```
