### ISSUE TITLE
очередная ошибка в Vcard

### ISSUE THREAD

**Issue by korobcov** [mrDoctorWho/vk4xmpp#149]
```python
| 13.12.2016 (07:26:55) |
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "modules/mod_iq_vcard.py", line 137, in vcard_handler
    vcard = buildVcard(VCARD_TEMPLATE)
TypeError: buildVcard() takes exactly 2 arguments (1 given)
```

**Comment by mrDoctorWho** [comment]
38f99047ae29861292a54bbd0eabb38fa30ce80a
