### ISSUE TITLE
Невалидный токен вызывает ошибку

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#165]
Не имеет смысла писать крашлог о том, что токен невалидный.

Достаточно просто упомянуть это в логах.

```python
| 17.02.2017 (20:21:31) |
Traceback (most recent call last):
  File "modules/mod_prs_main.py", line 22, in initializeUser
    user.connect()
  File "./gateway.py", line 602, in connect
    vk.auth()
  File "./gateway.py", line 290, in auth
    raise api.TokenError("The token is invalid (jid: %s, token: %s)" % (self.source, self.token))
TokenError: The token is invalid 
```

**Comment by mrDoctorWho** [comment]
4f78359cb1cdd5b544aa6eccb1475563394b7385
