### ISSUE TITLE
KeyError: 'name' in vcard_handler

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#173]
```python
| 18.02.2017 (10:38:50) |
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "modules/mod_iq_vcard.py", line 156, in vcard_handler
    data["screen_name"] = data["name"]
KeyError: 'name'
```

**Comment by mrDoctorWho** [comment]
3.8 всё.
