### ISSUE TITLE
OperationalError: too many terms in compound SELECT

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#186]
```python
| 17.03.2017 (07:58:35) |
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "extensions/avatar_hash.py", line 105, in handleQueue
    user.hashes = Avatars.makeHashes(user)
  File "extensions/avatar_hash.py", line 77, in makeHashes
    runDatabaseQuery(sql[:-1], set=True)
  File "./gateway.py", line 143, in runDatabaseQuery
    db(query, args)
  File "library/itypes.py", line 101, in <lambda>
    __call__ = lambda self, *args: self.execute(*args)
OperationalError: too many terms in compound SELECT
```

**Comment by mrDoctorWho** [comment]
Неактуально для mark 2, там не будет такой глупой системы.
