### ISSUE TITLE
RuntimeError: Either no token or password was given!

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#189]
```python
| 24.03.2017 (05:59:13) |
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "modules/mod_msg_main.py", line 77, in message_handler
    acceptCaptcha(args, source, jidTo)
  File "modules/mod_msg_main.py", line 36, in acceptCaptcha
    user.captchaChallenge(key)
  File "./gateway.py", line 810, in captchaChallenge
    self.reauth()
  File "./gateway.py", line 797, in reauth
    self.connect()
  File "./gateway.py", line 593, in connect
    raise RuntimeError("Either no token or password was given!")
RuntimeError: Either no token or password was given!
```

**Comment by mrDoctorWho** [comment]
Неактуально для mark 2.
