### ISSUE TITLE
AccessDenied: Access denied: can't set typing activity for this peer

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#190]
```python
| 16.03.2017 (11:18:48) |
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "modules/mod_msg_main.py", line 68, in message_handler
    user.vk.method("messages.setActivity", {"user_id": target, "type": "typing"}, True)
  File "./gateway.py", line 347, in method
    result = self.engine.method(method, args, notoken=notoken)
  File "library/vkapi.py", line 382, in method
    raise AccessDenied(eMsg)
AccessDenied: Access denied: can't set typing activity for this peer
```

**Comment by mrDoctorWho** [comment]
Наверное лучше это просто игнорировать.
