### ISSUE TITLE
KeyError: <ssl.SSLSocket object at 0x7f706f121ed8>

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#199]
```python
| 12.05.2017 (21:46:07) |
Traceback (most recent call last):
  File "library/utils.py", line 24, in execute
    result = handler(*list)
  File "library/longpoll.py", line 355, in watchdog
    del cls.__list[sock]
KeyError: <ssl.SSLSocket object at 0x7f706f121ed8>
```

**Comment by mrDoctorWho** [comment]
Скорее всего, не будет актуально для mark 2.
